---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Release
        id: setup-release
        uses: LizardByte/setup-release-action@fix!-updates  # todo: change to latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # can use GITHUB_TOKEN for read-only access

      - name: Create/Update GitHub Release
        if: ${{ steps.setup-release.outputs.publish_release == 'true' }}
        uses: LizardByte/create-release-action@fix!-updates  # todo: change to latest
        with:
          allowUpdates: false
          artifacts: ""
          discussionCategory: announcements
          generateReleaseNotes: true
          name: ${{ steps.setup-release.outputs.release_tag }}
          prerelease: true
          tag: ${{ steps.setup-release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
